title: ACs lilla fusklapp
subtitle: Vassego'!
# description: >- # this means to ignore newlines until "baseurl:"
#   This is the demo site for a Jekyll theme version of
#   HTML5 UP's sleek, responsive site template Prologue.
author: Malcolm Nihlén
email: malcolm.nihlen@roirekrytering.se
avatar: roi_white.png

# You'll want to customize url and baseurl for your own site:
baseurl: "/roi-help" # the subpath of your site, e.g. /blog
url: "https://scriptcoded.github.io" # the base hostname & protocol for your site

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
